server:
  port: 8888

spring:
  servlet:
    multipart:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@172.18.67.130:1521/engosbtst
    username: dsgc
    password: dsgc
    driver-class-name: oracle.jdbc.driver.OracleDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: oracle
  reasonable: true
  params: count
  support-methods-arguments: true